fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 3.2       # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'vendor/**/*'
  - 'bin/**/*'
  - 'db/**/*'
  - 'tmp/**/*'
  - '**/*':
    - Style/HashSyntax

plugins:                # default: []
  - standard-rails

extend_config:
  - .standard_ext.yml
